### ISSUE TITLE
Are you familiar for orientation detection(Rotation Detection) in c++, especially in dlib dnn?

### ISSUE THREAD

**Issue by newforrestgump001** [dlib-users/dnn#3]
Are you familiar for orientation detection(Rotation Detection) in c++? The output is rotated rectangle instead of horizontal bounding box. Thank you a lot for your advice!

**Comment by arrufat** [comment]
I have never tried myself, but doesn't seem that hard... You would need to modify the YOLO loss to output an extra feature (x, y, w, h, o, r) where r would be the rotation angle, and then train with rotated rectangles.

**Comment by arrufat** [comment]
No, I don't, what I'd like to do at some point though is to improve the bounding box regression, to be similar to the one in YOLOv4 and others, that is, to use cIOU.
